hook: true
typescript: true

commandDir: dist/bin/semo/commands
commandMakeDir: src/bin/semo/commands
cronDir: dist/bin/semo/crons
cronMakeDir: src/bin/semo/crons
pluginDir: dist/bin/semo/plugins
pluginMakeDir: src/bin/semo/plugins
extendDir: dist/bin/semo/extends
extendMakeDir: src/bin/semo/extends
scriptDir: dist/bin/semo/scripts
scriptMakeDir: src/bin/semo/scripts
hookDir: dist/bin/semo/hooks
hookMakeDir: src/bin/semo/hooks
migrationDir: dist/migration
migrationMakeDir: src/migration
modelDir: dist/model
modelMakeDir: src/model
controllerDir: dist/controller
controllerMakeDir: src/controller


# 采用主动注册插件的方式
$plugins:
  redis: true
  sequelize: true
  application: true
  cron: true
  hook: true
  script: true

$plugin:
  semo:

    # 给 REPL 顶层注入一些对象
    extract:
      - Semo.hooks.application
      - Semo.hooks.application.models
      - Semo.hooks.application.services
      - Semo.hooks.semoPluginRedis
      - Semo.hooks.semoPluginSequelize

  redis:
    defaultConnection: redis2
    connection:
      redis:
        host: 127.0.0.1
        port: 6379
      redis2:
        host: 192.168.31.126
        port: 6379

  sequelize:
    defaultConnection: d9
    connection:
      d8:
        host: localhost
        port: 5432
        username: d8
        password: d8
        database: d8
        dialect: postgres
        prefix: sm_
        raw: true
      d9:
        host: 192.168.31.126
        port: 3306
        username: root
        password: root
        database: d9
        dialect: mysql
        prefix: sm_
        raw: true
